/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.ManagerViews;

import Controllers.ManagerController;
import Controllers.SalesStatistics;
import Controllers.UserController;
import Models.Sales;
import Models.User;
import Views.ManagerDashboard;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adithya
 */
public class ManageSales extends javax.swing.JFrame {

    private DefaultTableModel salesTableModel;

    private Sales sale;
    private int selectedSalesId;
    private ManagerController manager;
    private UserController currentUser;
    private User user;

    public ManageSales(User user) {
        initComponents();
        manager = new ManagerController(user.getUserId(), user.getUsername(), user.getPassword(), user.getName(), user.getAddress(), user.getEmail(), user.getMobile(), user.getNic());
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        currentUser = new UserController();
        sale = new Sales();
        this.user = user;
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int confirmed = JOptionPane.showConfirmDialog(null,
                        "Are you sure you want to exit?", "Exit Confirmation",
                        JOptionPane.YES_NO_OPTION);

                if (confirmed == JOptionPane.YES_OPTION) {
                    dispose();// Close the window
                    // Optionally, perform actions to exit the application
                }
            }
        });
        salesTableModel = new DefaultTableModel();

        salesTableModel.addColumn(
                "SalesID");
        salesTableModel.addColumn(
                "ProductID");
        salesTableModel.addColumn(
                "UserID");
        salesTableModel.addColumn(
                "SoldQty");
        salesTableModel.addColumn(
                "Income");
        salesTableModel.addColumn(
                "Eminums");
        salesTableModel.addColumn(
                "InvoiceID");
        salesTableModel.addColumn(
                "Issued Date");

        // Set the table model for your sales table
        salesTable.setModel(salesTableModel);
        loadSaleData();
        getStats();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageSalesContainer = new javax.swing.JPanel();
        manageSalesNavContainer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblOpenManageProduct = new javax.swing.JLabel();
        lblOpenManageeUser = new javax.swing.JLabel();
        lblOpenManageDashboard = new javax.swing.JLabel();
        managerSalesBodyContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        txtInvoiceNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblStatIncome = new javax.swing.JLabel();
        lblStatQty = new javax.swing.JLabel();
        lblOpenManageSale = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMostSellerName = new javax.swing.JLabel();
        lblMostSellerUserId = new javax.swing.JLabel();
        lblMostSellerNic = new javax.swing.JLabel();
        lblMostSellerErnings = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        btnCalculateDailySale = new javax.swing.JButton();
        lblTotalDailyIncome = new javax.swing.JLabel();
        lblTotalDailyQty = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Manage Sales");

        manageSalesContainer.setBackground(new java.awt.Color(0, 102, 102));
        manageSalesContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageSalesNavContainer.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MANAGE SALES");

        btnLogout.setBackground(new java.awt.Color(0, 102, 102));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LogOut");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblOpenManageProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/productmanage.gif"))); // NOI18N
        lblOpenManageProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpenManageProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOpenManageProductMouseClicked(evt);
            }
        });

        lblOpenManageeUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/usermanage.gif"))); // NOI18N
        lblOpenManageeUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpenManageeUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOpenManageeUserMouseClicked(evt);
            }
        });

        lblOpenManageDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/home.gif"))); // NOI18N
        lblOpenManageDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpenManageDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOpenManageDashboardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout manageSalesNavContainerLayout = new javax.swing.GroupLayout(manageSalesNavContainer);
        manageSalesNavContainer.setLayout(manageSalesNavContainerLayout);
        manageSalesNavContainerLayout.setHorizontalGroup(
            manageSalesNavContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageSalesNavContainerLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 427, Short.MAX_VALUE)
                .addComponent(lblOpenManageDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOpenManageProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOpenManageeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        manageSalesNavContainerLayout.setVerticalGroup(
            manageSalesNavContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageSalesNavContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageSalesNavContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageSalesNavContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblOpenManageeUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblOpenManageProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblOpenManageDashboard, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        manageSalesContainer.add(manageSalesNavContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        managerSalesBodyContainer.setBackground(new java.awt.Color(255, 255, 255));

        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SalesID", "UserID", "ProductID", "SoldQty", "Income", "Eminums", "Invoiceid", "Issued Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(salesTable);
        if (salesTable.getColumnModel().getColumnCount() > 0) {
            salesTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            salesTable.getColumnModel().getColumn(1).setPreferredWidth(20);
            salesTable.getColumnModel().getColumn(2).setPreferredWidth(20);
            salesTable.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 102, 102));
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtInvoiceNumber.setBackground(new java.awt.Color(255, 255, 255));
        txtInvoiceNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtInvoiceNumber.setForeground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Invoice Number");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtInvoiceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(txtInvoiceNumber))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SALES STATS");

        lblStatIncome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStatIncome.setForeground(new java.awt.Color(0, 0, 0));
        lblStatIncome.setText("Total Income");

        lblStatQty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStatQty.setForeground(new java.awt.Color(0, 0, 0));
        lblStatQty.setText("Total Qty Sold:");

        lblOpenManageSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/salesmanage.gif"))); // NOI18N
        lblOpenManageSale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpenManageSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOpenManageSaleMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MOST SELLER");

        lblMostSellerName.setBackground(new java.awt.Color(0, 0, 0));
        lblMostSellerName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMostSellerName.setForeground(new java.awt.Color(0, 102, 102));
        lblMostSellerName.setText(" ");

        lblMostSellerUserId.setBackground(new java.awt.Color(0, 0, 0));
        lblMostSellerUserId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMostSellerUserId.setForeground(new java.awt.Color(0, 102, 102));
        lblMostSellerUserId.setText(" ");

        lblMostSellerNic.setBackground(new java.awt.Color(0, 0, 0));
        lblMostSellerNic.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMostSellerNic.setForeground(new java.awt.Color(0, 102, 102));
        lblMostSellerNic.setText(" ");

        lblMostSellerErnings.setBackground(new java.awt.Color(0, 0, 0));
        lblMostSellerErnings.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMostSellerErnings.setForeground(new java.awt.Color(0, 102, 102));
        lblMostSellerErnings.setText(" ");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/img/ezgif.com-resize (6).gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 172, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMostSellerErnings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMostSellerNic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMostSellerUserId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMostSellerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMostSellerName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMostSellerUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMostSellerNic, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMostSellerErnings, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblOpenManageSale, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(lblStatIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStatQty, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOpenManageSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStatIncome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStatQty)
                .addGap(56, 56, 56)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Daily Sales");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Enter Date:");

        txtDate.setBackground(new java.awt.Color(255, 255, 255));
        txtDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDate.setForeground(new java.awt.Color(0, 0, 0));
        txtDate.setText("YYYY-MM-DD");

        btnCalculateDailySale.setBackground(new java.awt.Color(0, 102, 102));
        btnCalculateDailySale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCalculateDailySale.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculateDailySale.setText("Calculate");
        btnCalculateDailySale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateDailySaleActionPerformed(evt);
            }
        });

        lblTotalDailyIncome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalDailyIncome.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalDailyIncome.setText(" ");

        lblTotalDailyQty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalDailyQty.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalDailyQty.setText(" ");

        btnClear.setBackground(new java.awt.Color(204, 51, 0));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout managerSalesBodyContainerLayout = new javax.swing.GroupLayout(managerSalesBodyContainer);
        managerSalesBodyContainer.setLayout(managerSalesBodyContainerLayout);
        managerSalesBodyContainerLayout.setHorizontalGroup(
            managerSalesBodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managerSalesBodyContainerLayout.createSequentialGroup()
                .addGroup(managerSalesBodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managerSalesBodyContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(managerSalesBodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(managerSalesBodyContainerLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(managerSalesBodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(managerSalesBodyContainerLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtDate)
                                .addGap(18, 18, 18)
                                .addComponent(btnCalculateDailySale, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managerSalesBodyContainerLayout.createSequentialGroup()
                                .addComponent(lblTotalDailyQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(106, 106, 106)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managerSalesBodyContainerLayout.createSequentialGroup()
                                .addComponent(lblTotalDailyIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(269, 269, 269)))
                        .addGap(27, 27, 27)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        managerSalesBodyContainerLayout.setVerticalGroup(
            managerSalesBodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerSalesBodyContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(managerSalesBodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managerSalesBodyContainerLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(managerSalesBodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(managerSalesBodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCalculateDailySale, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(managerSalesBodyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(managerSalesBodyContainerLayout.createSequentialGroup()
                                .addComponent(lblTotalDailyIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalDailyQty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(managerSalesBodyContainerLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managerSalesBodyContainerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(258, 258, 258))))
        );

        manageSalesContainer.add(managerSalesBodyContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageSalesContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageSalesContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadSaleData() {
        List<Sales> salesList = manager.viewAllSales(); // Retrieve product data

        // Clear existing data from the table
        salesTableModel.setRowCount(0);

        for (Sales sales : salesList) {
            // Add the product data to the table
            salesTableModel.addRow(new Object[]{
                sales.getSalesId(),
                sales.getProductId(),
                sales.getUserId(),
                sales.getSoldQuantity(),
                sales.getIncome(),
                sales.getEminum(),
                sales.getInvoiceId(),
                sales.getIssuedDate()
            });
        }
    }

    // Method to get statistics based on a specific date
    public void getStatisticsByDate(Date targetDate) {
        SalesStatistics salesStatistics = new SalesStatistics();
        List<Sales> salesData = manager.viewAllSales();

        int totalSoldQty = salesStatistics.calculateTotalSoldQuantityByDate(salesData, targetDate);
        double totalIncome = salesStatistics.calculateTotalIncomeByDate(salesData, targetDate);

        // Print or display the obtained statistics as needed
        lblTotalDailyQty.setText("Total Sold Quantity on " + targetDate + " is : " + totalSoldQty);
        lblTotalDailyIncome.setText("Total Income on " + targetDate + " is : $" + totalIncome);

    }

    public void getStats() {
        SalesStatistics salesStatistics = new SalesStatistics();
        List<Sales> salesData = manager.viewAllSales();

        int totalSoldQty = salesStatistics.calculateTotalQuantitySold(salesData);
        double totalIncome = salesStatistics.calculateTotalSales(salesData);

        // Print or display the obtained statistics as needed
        lblStatQty.setText("Total Sold Quantity : " + totalSoldQty);
        lblStatIncome.setText("Total Income: $" + totalIncome);

        User mostSalesUser = manager.getMostSalesUser();
        if (mostSalesUser != null) {
            // For example:
            lblMostSellerName.setText("Most Sales User: " + mostSalesUser.getName());
            lblMostSellerUserId.setText("Most Sales UserID: USER" + mostSalesUser.getUserId());
            lblMostSellerNic.setText("Most Sales NIC: " + mostSalesUser.getNic());
            lblMostSellerErnings.setText("Most Sales Earnings: $" + mostSalesUser.getTotalIncome());
        }
    }

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to Logout?", "Logout Confirmation",
                JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            currentUser.logout();
            dispose(); // Close the window
            // Optionally, perform actions to exit the application
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void lblOpenManageProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenManageProductMouseClicked
        openManageProductsForm();
    }//GEN-LAST:event_lblOpenManageProductMouseClicked

    private void lblOpenManageeUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenManageeUserMouseClicked
        openManageUsersForm();
    }//GEN-LAST:event_lblOpenManageeUserMouseClicked

    private void lblOpenManageSaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenManageSaleMouseClicked

    }//GEN-LAST:event_lblOpenManageSaleMouseClicked

    private void lblOpenManageDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenManageDashboardMouseClicked
        openManageDashboard();
    }//GEN-LAST:event_lblOpenManageDashboardMouseClicked

    private void btnCalculateDailySaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateDailySaleActionPerformed
        String dateStr = txtDate.getText();

        // Basic validation: Check if the date string is not empty
        if (!dateStr.isEmpty()) {
            try {
                // Attempt to parse the date string into a Date object
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                Date date = dateFormat.parse(dateStr);

                // Call method to get statistics by date if the date parsing is successful
                getStatisticsByDate(date);
            } catch (ParseException e) {
                // Handle the case where the date format is incorrect
                JOptionPane.showMessageDialog(this, "Please enter a valid date in the format yyyy-MM-dd.", "Invalid Date", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Display an error message if the date string is empty
            JOptionPane.showMessageDialog(this, "Please enter a date.", "Empty Date", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCalculateDailySaleActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        lblTotalDailyQty.setText(" ");
        lblTotalDailyIncome.setText(" ");
        txtDate.setText("");
        txtInvoiceNumber.setText("");
        loadSaleData();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchKeyword = txtInvoiceNumber.getText();

        // Assuming salesController is an instance of SalesController
        List<Sales> searchResults = manager.searchSalesByInvoiceId(searchKeyword);

        salesTableModel.setRowCount(0);
        if (!searchResults.isEmpty()) {
            for (Sales searchResult : searchResults) {
                salesTableModel.addRow(new Object[]{
                    searchResult.getSalesId(),
                    searchResult.getProductId(),
                    searchResult.getUserId(),
                    searchResult.getSoldQuantity(),
                    searchResult.getIncome(),
                    searchResult.getEminum(),
                    searchResult.getInvoiceId(),
                    searchResult.getIssuedDate()
                });

            }
        } else {
            // Display a message or handle the case where no result is found
            JOptionPane.showMessageDialog(ManageSales.this, "Failed to find the Invoice.", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnSearchActionPerformed

    private void openManageUsersForm() {
        if ("Manager".equals(user.getPosition())) {
            // Open ManagerForm with the user object
            java.awt.EventQueue.invokeLater(() -> {
                new ManageUsers(user).setVisible(true);
                this.dispose();
            });
        } else {
            JOptionPane.showMessageDialog(null, "You Dont Have Access.", "Error", JOptionPane.ERROR_MESSAGE);
        }// Calls the UserController method to open Manage Users form
    }

    private void openManageProductsForm() {
        if ("Manager".equals(user.getPosition())) {
            // Open ManagerForm with the user object
            java.awt.EventQueue.invokeLater(() -> {
                new ManageProduct(user).setVisible(true);
                this.dispose();
            });
        } else {
            JOptionPane.showMessageDialog(null, "You Dont Have Access.", "Error", JOptionPane.ERROR_MESSAGE);
        }// Calls the UserController method to open Manage Users form
    }

    private void openManageSalesForm() {
        if ("Manager".equals(user.getPosition())) {
            // Open ManagerForm with the user object
            java.awt.EventQueue.invokeLater(() -> {
                new ManageSales(user).setVisible(true);
                this.dispose();
            });
        } else {
            JOptionPane.showMessageDialog(null, "You Dont Have Access.", "Error", JOptionPane.ERROR_MESSAGE);
        }// Calls the UserController method to open Manage Users form
    }

    private void openManageDashboard() {
        if ("Manager".equals(user.getPosition())) {
            // Open ManagerForm with the user object
            java.awt.EventQueue.invokeLater(() -> {
                new ManagerDashboard(user).setVisible(true);
                this.dispose();
            });
        } else {
            JOptionPane.showMessageDialog(null, "You Dont Have Access.", "Error", JOptionPane.ERROR_MESSAGE);
        }// Calls the UserController method to open Manage Users form
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculateDailySale;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMostSellerErnings;
    private javax.swing.JLabel lblMostSellerName;
    private javax.swing.JLabel lblMostSellerNic;
    private javax.swing.JLabel lblMostSellerUserId;
    private javax.swing.JLabel lblOpenManageDashboard;
    private javax.swing.JLabel lblOpenManageProduct;
    private javax.swing.JLabel lblOpenManageSale;
    private javax.swing.JLabel lblOpenManageeUser;
    private javax.swing.JLabel lblStatIncome;
    private javax.swing.JLabel lblStatQty;
    private javax.swing.JLabel lblTotalDailyIncome;
    private javax.swing.JLabel lblTotalDailyQty;
    private javax.swing.JPanel manageSalesContainer;
    private javax.swing.JPanel manageSalesNavContainer;
    private javax.swing.JPanel managerSalesBodyContainer;
    private javax.swing.JTable salesTable;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtInvoiceNumber;
    // End of variables declaration//GEN-END:variables

}
